version: "2.0"
services:
  postgres:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  redis:
    image: redis:5-alpine
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data

  web:
    build:
      context: ./
    image: sparkworkshop
    restart: always
    entrypoint: ./entrypoint.sh
    environment:
      - DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
      - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB
      - SECRET_KEY=$SECRET_KEY
      - NEW_RELIC_ENVIRONMENT=$NEW_RELIC_ENVIRONMENT
    volumes:
      - ./data/media:/code/sparkWorkshop/media
      - ./data/public:/code/sparkWorkshop/public
      - .:/code
    depends_on:
      - postgres
      - redis

  # celery:
  #   build:
  #     context: ./
  #   image: sparkworkshop
  #   restart: always
  #   working_dir: /code/sparkworkshop
  #   entrypoint: celery -A sparkworkshop worker -l INFO
  #   environment:
  #     - C_FORCE_ROOT="true"
  #     - DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
  #     - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB
  #     - SECRET_KEY=$SECRET_KEY
  #     - googleads_developer_token=$googleads_developer_token
  #     - googleads_client_customer_id=$googleads_client_customer_id
  #     - googleads_client_id=$googleads_client_id
  #     - googleads_client_secret=$googleads_client_secret
  #     - googleads_refresh_token=$googleads_refresh_token
  #   depends_on:
  #     - web

  # beat:
  #   build:
  #     context: ./
  #   image: sparkworkshop
  #   restart: always
  #   working_dir: /code/sparkworkshop
  #   entrypoint: celery -A sparkworkshop beat -l INFO
  #   environment:
  #     - C_FORCE_ROOT="true"
  #     - DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
  #     - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB
  #     - SECRET_KEY=$SECRET_KEY
  #   depends_on:
  #     - web

  nginx:
    image: nginx
    restart: always
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=$NGINX_HOST
      - PROXY_PASS=http://web:8888
    command: /bin/bash -c "envsubst '$${NGINX_HOST},$${PROXY_PASS}' < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    volumes:
      - ./deploy/nginx.template:/etc/nginx/conf.d/nginx.template
      - ./data/media:/web/media:ro
      - ./data/public:/web/public:ro
    depends_on:
      - web
